### ISSUE TITLE
Quest grammer

### ISSUE THREAD

**Issue by lawvs** [Gizeta/kcdata#107]
[plugin-quest](https://github.com/poooi/plugin-quest) 还没有 requirements.category.or 的语法
~~我也不知道为什么这么久了都没有”或“任务~~

> 237 B138 「羽黒」「神風」、出撃せよ！
> 
> 第五战队任务：「羽黒」「神风」作为基干，其他重巡級1艘驱逐舰2艘，或者驱逐舰4艘的舰队，出击南西诸岛近海、巴士海峡、東部奥廖尔海，与敌舰队交战并击灭他们！
> 
> 羽黑+神风，其他CA/CAV+2DD的5船阵容，或者其他4DD的6船阵容，出击2-1、2-2、2-3并获得S胜。
> 

羽黒 + 神风 + 2DD + CA/CAV
OR
羽黒 + 神风 + 4DD

->

羽黒 + 神风 + 2DD + **1CA/1CAV/2DD** 
([现有语法](https://github.com/poooi/plugin-quest/blob/master/reqstr.es#L101-L154)难以描述，可以用note注释，但无法兼顾 i18n

pr见#100

**Comment by lawvs** [comment]
> 620 F88 一航戦精鋭'流星改'隊の編成
> 
> 一航戦任務：旗艦「赤城改二（改二戊）」第一装備スロに「流星改（一航戦）」※連度maxを搭載し、「流星改」×4「彩雲」×1「九七艦攻」×2廃棄、弾薬×2800、ボーキ9000、熟練搭乗員×2を準備せよ！
> 一航战任务：将“赤城改二（戊）”作为旗舰，并在第一格装备熟练度max的“流星改(一航战)”，废弃“流星改”4架，“彩云”1架，“九七式舰攻”2架，并准备2800弹药、9000铝土、以及熟练搭乘员2名！

enhance requirements(modelconversion).[use_skilled_crew](https://github.com/poooi/plugin-quest/blob/master/reqstr.es#L518-L520) for 熟練搭乗員×2

**Comment by KagamiChan** [comment]
这两个问题我有时间的时候会看一下。代码时间有点长了，需要再捡起来

**Comment by lawvs** [comment]
OR 语法已添加

熟练搭乘员2名 将由 kcwikizh/kcwiki-quest-data#28 跟踪
