### ISSUE TITLE
[Wrong data] Quest 0

### ISSUE THREAD

**Issue by LolesszzZZZ** [Gizeta/kcdata#113]
poi任務信息插件 顯示不出任何任務

**Comment by daarklord** [comment]
Yeah all the quest information is missing.

https://imgur.com/KuZTjnq

**Comment by KagamiChan** [comment]
Hi @LolesszzZZZ and @daarklord 
The issue has been fixed, please check the latest version 5.5.10

**Comment by LolesszzZZZ** [comment]
Hi there,

It is so fast! Thanks for your excellent service!

Good night.

Loo Liangnyi
