### ISSUE TITLE
[Wrong Data] Quest F65 / 673

### ISSUE THREAD

**Issue by RM-801** [Gizeta/kcdata#12]
多了一个逗号，希望能改正

**Comment by lawvs** [comment]
我仔细检查了 kcdata/quest/poi.json 的 F65 / 673 ，没有发现多余的逗号。。能详细指出在哪吗。。多谢了
```json
  {
    "game_id": 673,
    "wiki_id": "F65",
    "category": 6,
    "type": 2,
    "name": "装備開発力の整備",
    "detail": "工廠整備任務：装備開発力を整備する。「小口径主砲」系装備x4を廃棄せよ！",
    "reward_fuel": 0,
    "reward_ammo": 0,
    "reward_steel": 100,
    "reward_bauxite": 0,
    "reward_other": [
      {
        "name": "開発資材",
        "amount": 1
      }
    ],
    "prerequisite": [
      607
    ],
    "requirements": {
      "category": "equipexchange",
      "scraps": [
        {
          "name": "小口径主砲",
          "amount": 4
        }
      ]
    }
  },
```

**Comment by KagamiChan** [comment]
类型用错了，应该和 F34 一样用 `scrapequipment`
`equipexchange` 是需要写消耗资源的

**Comment by lawvs** [comment]
已提交pr，感谢指正🌹

**Comment by KagamiChan** [comment]
`scrapequipment` 所需要的字段和 `equipexchange` 是不一样的，只改类型是不行的，参考 F34 的字段

我这边下次更新数据的时候会对数据能否正确解析做检查

**Comment by lawvs** [comment]
🤯能否提供plugin-quest插件使用的data.json文件位置，我下次提交前先进行本地验证

是这个吗？
"..\AppData\Roaming\poi\plugins\node_modules\poi-plugin-quest-info\assets\info\index.json"

**Comment by KagamiChan** [comment]
现在换到了 assets/data.json 下面

**Comment by KagamiChan** [comment]
简单写了一个验证的界面，下次维护数据的时候可以拿来验证一下
https://github.com/KagamiChan/plugin-quest-devtool

![image](https://user-images.githubusercontent.com/3816900/35173733-7700e67c-fda7-11e7-8bb3-039cce91eec6.png)

**Comment by lawvs** [comment]
多谢
