### ISSUE TITLE
[Wrong Data] Quest A83 / 188

### ISSUE THREAD

**Issue by MorrisChen1998** [Gizeta/kcdata#124]
此任務應該是長波改二+高波改and沖波改and朝霜改而不是上面寫的高波改/沖波改/朝霜改任一隻

**Comment by lawvs** [comment]
查閱了其他 wiki ，描述均是任一隻。任務描述也說明了是 _または_ 和  _2隻艦隊_

> 編成任務：「長波改二」旗艦、僚艦に「高波改」または「沖波改」「朝霜改」を配した、第三一駆逐隊第一小隊(**2隻艦隊**)を編成せよ！

[英 wiki](https://kancolle.fandom.com/wiki/Quests#A83)

> Have Naganami Kai Ni as flagship and 1 of Takanami Kai, Okinami Kai, and Asashimo Kai in your fleet.
