### ISSUE TITLE
[Wrong Data] Quest Bq07 / 888 出现乱码

### ISSUE THREAD

**Issue by Amemiyasora** [Gizeta/kcdata#144]
您好，插件中很多任务出现了&amp;amp:#x2F这个乱码
![QQ截图20200617200945](https://user-images.githubusercontent.com/28768821/84896414-82131500-b0d6-11ea-978f-cbf0863131c7.png)

**Comment by lawvs** [comment]
非常抱歉，这边会尽快修复
