### ISSUE TITLE
[Wrong Data] Quest C15 / 317

### ISSUE THREAD

**Issue by q68123** [Gizeta/kcdata#155]
描述为夕云阳炎级均可，但是2-2的时候我使用了卷云和阳炎，直到推完2-5却显示完成度80%，其中2-3~2-5期间均使用阳炎+浜风的配置，遂以同配置（阳炎+浜风）回推2-2即显示任务完成。具体原因未知，不知是卷云的问题还是配置切换的问题。

**Comment by lawvs** [comment]
配置切换理论上不会影响这个任务的进度，我们目前没有收到这个任务的其他错误报告，因此也难以确认`巻雲`是否无法完成该任务。

如果后续有其他更明确的证据表明这个任务信息存在错误或遗漏，我们会及时进行修复。

你有其他认为有用的信息也可以补充，感谢你的反馈。

---

_如果后续没有其他讨论，这个问题将会在一段时间后被关闭。_

**Comment by q68123** [comment]
通过对出击记录的分析得出结论了，是打2-2的时候演习次数没有打够，故2-2没有被记录进去，应该是必须先完成3次演习才可开始记录推图的任务进度。如有需要可以提供战斗记录截图，感谢回复！

**Comment by lawvs** [comment]
我们将会在这个任务中使用`之后`而不是`以及`作为连词来明确语义。非常抱歉给你带来不便。

> 演习胜利3次，限一日内，需要夕雲级/陽炎级2只；**之后**2-2,2-3,2-4,2-5Boss战获得A胜或以上1次，需要夕雲级/陽炎级2只
