### ISSUE TITLE
[Wrong Data] Quest B99 / 856

### ISSUE THREAD

**Issue by IkenaiKanchou** [Gizeta/kcdata#193]
缺失在第一舰队配置

**Comment by lawvs** [comment]
在舰百和日 wiki 都没有看到需要配置在第一舰队的描述，我们将会在收集到更多信息之后进行核实更新，仍然感谢你的反馈

> 新编“第一战队”出击任务：配备以战舰“长门改二”为旗舰、以“陆奥改”为二号舰的第一舰队来进行出击！前往咖喱洋里兰卡岛海域（4-5）和沙门海域北方（5-5），捕捉本海域的敌方舰队主力，并歼灭她们！
> --舰队百科


日 wiki
<img width="1005" alt="日 wiki B99" src="https://user-images.githubusercontent.com/18554747/116914771-c1f6d280-ac7d-11eb-89a4-466b11ea36e7.png">
