### ISSUE TITLE
[Wrong Data] Quest B16 / 227

### ISSUE THREAD

**Issue by IkenaiKanchou** [Gizeta/kcdata#194]
缺失在第一舰队配置

**Comment by lawvs** [comment]
在舰百和日 wiki 都没有看到需要配置在第一舰队的描述

我们将会在收集到足够可靠的信息之后进行核实更新，非常感谢你的反馈

> 派出完全编成的“三川舰队”，消灭东部奥廖尔海(2-3)的敌人！
> --舰娘百科

> 完全編成した「三川艦隊」をもって、オリョール海の敵を撃滅せよ！
> ※「敵主力打撃群」(2-3ボス戦)にB勝利以上で達成
> ※「新三川艦隊」(「鳥海」+「青葉」+「衣笠」+「加古」+「古鷹」+「天龍」の6隻)なので注意
> --日 wiki
