### ISSUE TITLE
[Wrong data] Quest 657

### ISSUE THREAD

**Issue by KonGo1921** [Gizeta/kcdata#219]
F92  新型兵装開発整備の強化   
新型兵装の開発体制整備を実施する！「小口径主砲」系装備×6、「中口径主砲」系装備×5、「魚雷」系装備×4を廃棄、鋼材4,000を準備せよ！　※任務達成後、準備した資源は消費します。
※进行新型兵装的开发体制整备！将“小口径主炮”系装备×6  “中口径主炮”系装备×5  “鱼雷”系装备×4废弃，并准备4000钢材！　※任务完成后，准备的资源会被消耗掉。

[开发资材]×10
从下列奖励中选择一项：
[改修资材]×5
[新型兵装资材])×2

**Comment by lawvs** [comment]
擴展程式 任務信息 已經不再維護了，推薦使用 任務信息2 獲取最新的任務信息

你可以在 擴展程式 面板直接下載這個插件

![image](https://user-images.githubusercontent.com/18554747/191001530-cbac46bd-35ee-4c23-9506-9740a14d76d1.png)
