### ISSUE TITLE
[Wrong Data] Quest C16 / 318

### ISSUE THREAD

**Issue by Pig-Platinum** [Gizeta/kcdata#23]
伊良湖月常任务描述有重复文字

**Comment by lawvs** [comment]
很抱歉为了能够实现多语言的自动翻译, 部分任务的完成条件在保证原意不变的情况下会有一定的冗余, 我们已经联系了插件作者进行优化, 感谢您的反馈, 对此给您带来的困扰，我们深感抱歉。

相关的讨论可以参见 #16
