### ISSUE TITLE
数据内容使用咨询

### ISSUE THREAD

**Issue by andychucs** [Gizeta/kcdata#232]
我最近在接入使用 ship/all.json，发现这里面有很多空值条目，这个项目可以做到条件过滤吗？
除了空值还有差分立绘的数据对我也是多余的

**Comment by Gizeta** [comment]
可以。页面都是托管到 GitHub Pages 静态生成的，你可以写一份自己的模板，只输出自己想要的数据，然后放到 `ship` 目录下，每次修改都会自动部署到 Github Pages。如果需要参考的话，可以看这个 [ship/ship.json](https://github.com/kcwikizh/kcdata/blob/gh-pages/ship/ship.json) 或 [slotitem/poi_improve.json](https://github.com/kcwikizh/kcdata/blob/gh-pages/slotitem/poi_improve.json)

模板：https://jekyllrb.com/
语法：https://shopify.github.io/liquid/basics/introduction/

**Comment by andychucs** [comment]
👍
我之前看到ship.json了，但是看起来数据有点问题，最后会比all.json多一个“,”导致数据不符合json规范。与all.json对比，我没有看出来它有没有语法错误。
<img width="860" alt="截屏2023-08-26 18 50 30" src="https://github.com/kcwikizh/kcdata/assets/24852023/d31f4c9f-c471-433b-9396-73d198430c4a">

**Comment by Gizeta** [comment]
hmmmm，最后多一个逗号应该是个bug，之前没注意过这个文件，我修下

**Comment by Gizeta** [comment]
`ship` 多一个逗号的问题已经修复了
