### ISSUE TITLE
[Wrong Data] Quest B105 / 864

### ISSUE THREAD

**Issue by Ice9Coffee** [Gizeta/kcdata#24]
任务奖励描述中：”从以下 %s 项中选择一项“
第一条中%s -> 3
第二条中%s -> 2

**Comment by KagamiChan** [comment]
这个是插件这边的问题，咕咕咕

**Comment by KagamiChan** [comment]
这个感觉应该是已经修了

**Comment by lawvs** [comment]
https://github.com/poooi/plugin-quest/commit/6bf23ec54e31edefdfcbf41d741ab17593f8c86a
