### ISSUE TITLE
_slotitem/151.json

### ISSUE THREAD

**Issue by andychucs** [Gizeta/kcdata#271]
https://github.com/kcwikizh/kcdata/blob/b0eff00538c2ec6a1718b791b10cfbf12b1d19a9/_slotitem/151.json#L72
json parse error on [poi_improve.json](https://kcwikizh.github.io/kcdata/slotitem/poi_improve.json)
<img width="332" alt="截屏2024-07-16 00 34 27" src="https://github.com/user-attachments/assets/d0469b8a-923a-4c23-aa26-106eef03b06b">

**Comment by Gizeta** [comment]
Fixed.
