### ISSUE TITLE
[Wrong Data] Quest F61 / 669

### ISSUE THREAD

**Issue by Ice9Coffee** [Gizeta/kcdata#28]
完成条件还需要消耗5000铝

**Comment by lawvs** [comment]
关于机种转换额外资源消耗不显示的问题已经在插件中修复，请~~耐心~~等待插件下一个版本发布，感谢您的反馈, 给您带来不便，敬请谅解。

修复细节可以查看 [plugin-quest#46](https://github.com/poooi/plugin-quest/pull/46)

**Comment by lawvs** [comment]
任务插件新版本已发布，请更新插件修复这个问题~~同时引入更多问题~~
