### ISSUE TITLE
关于任务信息

### ISSUE THREAD

**Issue by Sunev** [Gizeta/kcdata#3]
能否请问一下[poi.json](https://github.com/kcwikizh/kcdata/commits/gh-pages/quest/poi.json)的更新计划？
如果有需要的话我想我乐意提交一些pr

**Comment by Gizeta** [comment]
poi格式的任务虽然是有脚本来转换kcwiki任务格式的，实际上现在的任务越来越复杂了，再加上双方格式的不同，几乎已经成了每个id都硬编码任务内容了([code](https://bitbucket.org/Gizeta_sf/kcdata/src/0a4039c48ab5e5995b9d37d151d286f397d26f5d/scripts/poi_quest.rb?at=master&fileviewer=file-view-default#poi_quest.rb-5))。所以一直更新较慢。最近是被kcwiki站长催着更新任务数据啦，不过实际要更新我这边可能还需要等几天（其他事有些忙，更新任务没法脚本自动化很麻烦）。

pr是非常欢迎的。如果是只针对poi.json的话，只更新那个json即可。

顺便吐槽一下现状吧。田中的任务越来越复杂，现有的kcwiki格式，还是poi格式都没法完美地描述任务内容。如果能提出一个更好的任务描述方案那就真是帮大忙了。

**Comment by KagamiChan** [comment]
附议，欢迎 pr
