### ISSUE TITLE
[Wrong Data] Quest B88 / 839

### ISSUE THREAD

**Issue by massan16** [Gizeta/kcdata#46]
現在の表記：戦艦/航戦（旗艦）+戦艦/航戦１隻+空母２隻+艦２隻で3-3ボスに１回S勝利
違う部分：本来の条件は「戦艦/航戦（旗艦）+戦艦/航戦１隻+艦４隻で3-3ボスに１回S勝利」である。

不同的部分：航空母舰２+自由２不同。正确地自由４。

sry,I'm JP.Translate by Google.

**Comment by lawvs** [comment]
申し訳ありません，第一期へ空母2隻以上はボスルートへの分岐条件
修正されました、フィードバックありがとう

**Comment by massan16** [comment]
修正に感謝します。

I am grateful for the correction.
