### ISSUE TITLE
[Wrong data] Quest 890

### ISSUE THREAD

**Issue by Ice9Coffee** [Gizeta/kcdata#49]
**任务未收录**

B122　精鋭「四戦隊」第二小隊、抜錨せよ！

「摩耶改二」及び「鳥海改二」から成る精鋭「第四戦隊」第二小隊を含む有力な艦隊を編成、南西諸島防衛線、東部オリョール海、アルフォンシーノ方面、カレー洋リランカ島沖に出撃、敵を撃滅せよ！

※將「摩耶改二」和「鳥海改二」與其餘任意4艘船編成為精銳「四戰隊」第二小隊，出擊1-4、2-3、3-3、4-5並取得Boss點S勝利。
1-4,2-3可以洗地流，3-3 2(cv or bb)2ca2dd，4-5建議3CA3CV。建議4-5在磨血階段完成此任務。

奖励：
油400 | 弹400 | 钢0 | 铝400
家具【「摩耶の盾」掛け軸】 
從下列獎勵中選擇一項：
12.7cm連裝高角炮(後期型)×1
高速修復材×8
勳章×1

單次出擊任務
「第四戦隊」出撃せよ！」(B13)、「演習」で練度向上！(C2) 待驗證

*以上转自萌娘百科*
https://zh.moegirl.org/%E8%88%B0%E9%98%9FCollection%2F%E4%BB%BB%E5%8A%A1

**Comment by lawvs** [comment]
安排上了，感谢反馈
7f3921905047a6bf1cc59406186fc6b213bf64ae
