### ISSUE TITLE
[Wrong Data] Quest B41 / 273

### ISSUE THREAD

**Issue by AuTa** [Gizeta/kcdata#51]
遗漏前置任务：「三川艦隊」を新編、突入準備せよ！

**Comment by lawvs** [comment]
`B41 新編「三川艦隊」ソロモン方面へ！`的直接前置是`C5 精鋭艦隊演習`

`C5 精鋭艦隊演習`的前置才是`A50 「三川艦隊」を新編、突入準備せよ！`

`B41  -> C5 -> A50`

因此A50是不作为B41的直接前置的，详细可以查看[舰娘百科 - 任务 #B41](https://zh.kcwiki.org/wiki/%E4%BB%BB%E5%8A%A1#B41)

仍然感谢你的反馈
