### ISSUE TITLE
[Wrong data] Quest 299

### ISSUE THREAD

**Issue by Ice9Coffee** [Gizeta/kcdata#55]
11月16日新实装任务未收录

https://zh.moegirl.org/%E8%88%B0%E9%98%9FCollection/%E4%BB%BB%E5%8A%A1#11.E6.9C.8816.E6.97.A5.E6.96.B0.E5.AE.9E.E8.A3.85.E4.BB.BB.E5.8A.A1

**Comment by lawvs** [comment]
拖了这么久实在很抱歉
