### ISSUE TITLE
[Wrong Data] Quest A86 / 191

### ISSUE THREAD

**Issue by AuTa** [Gizeta/kcdata#56]
萌娘百科显示前置任务包括 B61。我自己的 F72 完成了，A86 没有出现。
https://zh.moegirl.org/舰队Collection/任务#A86

**Comment by lawvs** [comment]
可能是基础的日常任务没有完成？

**Comment by AuTa** [comment]
日本 wiki 也是需要 B61 的：https://wikiwiki.jp/kancolle/任務#id-A86

**Comment by lawvs** [comment]
尴尬，没仔细看，应该是前置更新的时候没有同步，已更新，感谢反馈！
