### ISSUE TITLE
[Wrong Data] Quest Bq05 / 873

### ISSUE THREAD

**Issue by taroxd** [Gizeta/kcdata#57]
任务仅要求轻1，二期后 3-2 不再要求轻1驱5。

From wiki:
> ボスマスへたどり着ける編成が極めて限定される、かなり特殊な海域。
具体的には、駆逐艦4隻を必須とし、残りは駆逐艦2隻 ・ 駆逐艦1隻+軽巡洋艦1隻 ・ 補給艦1隻+軽巡洋艦1隻のいずれかとなる。

**Comment by lawvs** [comment]
感谢反馈😁
